# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ml.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ml.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x08ml.proto\"\x1d\n\x0cTokenRequest\x12\r\n\x05token\x18\x01 \x01(\t\")\n\rImportRequest\x12\x18\n\x05\x66iles\x18\x01 \x03(\x0b\x32\t.FileData\"\x9d\x01\n\rActionRequest\x12.\n\x0b\x61\x63tion_type\x18\x01 \x01(\x0e\x32\x19.ActionRequest.ActionType\"\\\n\nActionType\x12\x0b\n\x07PREDICT\x10\x00\x12\n\n\x06\x45XPORT\x10\x01\x12\x12\n\x0e\x43REATE_DATASET\x10\x02\x12\x08\n\x04LOGS\x10\x03\x12\x17\n\x13\x44OWNLOAD_CHECKPOINT\x10\x04\"\"\n\rSetUpResponse\x12\x11\n\tml_status\x18\x01 \x01(\t\"#\n\x0eImportResponse\x12\x11\n\tml_status\x18\x02 \x01(\t\"#\n\x0e\x41\x63tionResponse\x12\x11\n\tml_status\x18\x03 \x01(\t\"-\n\x08\x46ileData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x32\x9a\x01\n\x0fMachineLearning\x12&\n\x05SetUp\x12\r.TokenRequest\x1a\x0e.SetUpResponse\x12+\n\x06Import\x12\x0e.ImportRequest\x1a\x0f.ImportResponse\"\x00\x12\x32\n\rPerformAction\x12\x0e.ActionRequest\x1a\x0f.ActionResponse\"\x00\x62\x06proto3'
)



_ACTIONREQUEST_ACTIONTYPE = _descriptor.EnumDescriptor(
  name='ActionType',
  full_name='ActionRequest.ActionType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PREDICT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EXPORT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CREATE_DATASET', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGS', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DOWNLOAD_CHECKPOINT', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=152,
  serialized_end=244,
)
_sym_db.RegisterEnumDescriptor(_ACTIONREQUEST_ACTIONTYPE)


_TOKENREQUEST = _descriptor.Descriptor(
  name='TokenRequest',
  full_name='TokenRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='TokenRequest.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=12,
  serialized_end=41,
)


_IMPORTREQUEST = _descriptor.Descriptor(
  name='ImportRequest',
  full_name='ImportRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='files', full_name='ImportRequest.files', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=84,
)


_ACTIONREQUEST = _descriptor.Descriptor(
  name='ActionRequest',
  full_name='ActionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action_type', full_name='ActionRequest.action_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ACTIONREQUEST_ACTIONTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=244,
)


_SETUPRESPONSE = _descriptor.Descriptor(
  name='SetUpResponse',
  full_name='SetUpResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ml_status', full_name='SetUpResponse.ml_status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=280,
)


_IMPORTRESPONSE = _descriptor.Descriptor(
  name='ImportResponse',
  full_name='ImportResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ml_status', full_name='ImportResponse.ml_status', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=317,
)


_ACTIONRESPONSE = _descriptor.Descriptor(
  name='ActionResponse',
  full_name='ActionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ml_status', full_name='ActionResponse.ml_status', index=0,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=319,
  serialized_end=354,
)


_FILEDATA = _descriptor.Descriptor(
  name='FileData',
  full_name='FileData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='FileData.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='FileData.content', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=401,
)

_IMPORTREQUEST.fields_by_name['files'].message_type = _FILEDATA
_ACTIONREQUEST.fields_by_name['action_type'].enum_type = _ACTIONREQUEST_ACTIONTYPE
_ACTIONREQUEST_ACTIONTYPE.containing_type = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['TokenRequest'] = _TOKENREQUEST
DESCRIPTOR.message_types_by_name['ImportRequest'] = _IMPORTREQUEST
DESCRIPTOR.message_types_by_name['ActionRequest'] = _ACTIONREQUEST
DESCRIPTOR.message_types_by_name['SetUpResponse'] = _SETUPRESPONSE
DESCRIPTOR.message_types_by_name['ImportResponse'] = _IMPORTRESPONSE
DESCRIPTOR.message_types_by_name['ActionResponse'] = _ACTIONRESPONSE
DESCRIPTOR.message_types_by_name['FileData'] = _FILEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenRequest = _reflection.GeneratedProtocolMessageType('TokenRequest', (_message.Message,), {
  'DESCRIPTOR' : _TOKENREQUEST,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:TokenRequest)
  })
_sym_db.RegisterMessage(TokenRequest)

ImportRequest = _reflection.GeneratedProtocolMessageType('ImportRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTREQUEST,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ImportRequest)
  })
_sym_db.RegisterMessage(ImportRequest)

ActionRequest = _reflection.GeneratedProtocolMessageType('ActionRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONREQUEST,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ActionRequest)
  })
_sym_db.RegisterMessage(ActionRequest)

SetUpResponse = _reflection.GeneratedProtocolMessageType('SetUpResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETUPRESPONSE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:SetUpResponse)
  })
_sym_db.RegisterMessage(SetUpResponse)

ImportResponse = _reflection.GeneratedProtocolMessageType('ImportResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTRESPONSE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ImportResponse)
  })
_sym_db.RegisterMessage(ImportResponse)

ActionResponse = _reflection.GeneratedProtocolMessageType('ActionResponse', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONRESPONSE,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:ActionResponse)
  })
_sym_db.RegisterMessage(ActionResponse)

FileData = _reflection.GeneratedProtocolMessageType('FileData', (_message.Message,), {
  'DESCRIPTOR' : _FILEDATA,
  '__module__' : 'ml_pb2'
  # @@protoc_insertion_point(class_scope:FileData)
  })
_sym_db.RegisterMessage(FileData)



_MACHINELEARNING = _descriptor.ServiceDescriptor(
  name='MachineLearning',
  full_name='MachineLearning',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=404,
  serialized_end=558,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetUp',
    full_name='MachineLearning.SetUp',
    index=0,
    containing_service=None,
    input_type=_TOKENREQUEST,
    output_type=_SETUPRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Import',
    full_name='MachineLearning.Import',
    index=1,
    containing_service=None,
    input_type=_IMPORTREQUEST,
    output_type=_IMPORTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='PerformAction',
    full_name='MachineLearning.PerformAction',
    index=2,
    containing_service=None,
    input_type=_ACTIONREQUEST,
    output_type=_ACTIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MACHINELEARNING)

DESCRIPTOR.services_by_name['MachineLearning'] = _MACHINELEARNING

# @@protoc_insertion_point(module_scope)
